---
- name: Create containers and connect to network
  docker_container:
    name: db_test
    image: "{{ item }}"
    networks:
      - name: "{{ docker_network_name }}"
    mounts:
      target: #path inside container 
      source: #path outside container
      read_only: yes # crowdsec 
  with_items:
    - "traefik:latest"
    - "authelia/authelia:latest"
    - "nginx:latest" 
    - "crowdsecurity/crowdsec:latest"
    - "crowdsecurity/cloudflare-bouncer"
    - "fbonalair/traefik-crowdsec-bouncer"